//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Accommodation</summary>
	[PublishedContentModel("accommodation")]
	public partial class Accommodation : PublishedContentModel, INavigation, IPageHeaderText
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "accommodation";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Accommodation(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Accommodation, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Description: The meta description is what appears together with your site's name on a google search. It appears below the site name, recommended length is 130 words
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta tags: Comma separated list that describes what your site is about. Modern browsers ignore this so it is not required. Could still do some good when included though
		///</summary>
		[ImplementPropertyType("metaTags")]
		public string MetaTags
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetMetaTags(this); }
		}

		///<summary>
		/// Page Title: The Page title is what you see in the browser's tab when you are on a page
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetPageTitle(this); }
		}

		///<summary>
		/// Show this page: Shows this page in the top navigation bar
		///</summary>
		[ImplementPropertyType("pageVisible")]
		public bool PageVisible
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetPageVisible(this); }
		}

		///<summary>
		/// Header Text: Your page header
		///</summary>
		[ImplementPropertyType("headerText")]
		public string HeaderText
		{
			get { return Umbraco.Web.PublishedContentModels.PageHeaderText.GetHeaderText(this); }
		}
	}
}
