//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Contact Us</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : PublishedContentModel, INavigation, IPageHeaderText
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address: Street Town City Country
		///</summary>
		[ImplementPropertyType("detailsAddress")]
		public IEnumerable<string> DetailsAddress
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("detailsAddress"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("detailsEmail")]
		public string DetailsEmail
		{
			get { return this.GetPropertyValue<string>("detailsEmail"); }
		}

		///<summary>
		/// Header: Header text for contact details
		///</summary>
		[ImplementPropertyType("detailsHeader")]
		public string DetailsHeader
		{
			get { return this.GetPropertyValue<string>("detailsHeader"); }
		}

		///<summary>
		/// Phone Number: country code - area code - 123 - 123 - 123
		///</summary>
		[ImplementPropertyType("detailsPhoneNumber")]
		public string DetailsPhoneNumber
		{
			get { return this.GetPropertyValue<string>("detailsPhoneNumber"); }
		}

		///<summary>
		/// Meta Description: The meta description is what appears together with your site's name on a google search, it appears below the site name. The recommended length is 130 words
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta tags: Comma separated list that describes what your site is about. Modern browsers ignore this so it is not required. Not harmful to add though
		///</summary>
		[ImplementPropertyType("metaTags")]
		public string MetaTags
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetMetaTags(this); }
		}

		///<summary>
		/// Page Title: The Page title is what you see in the browser's tab
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetPageTitle(this); }
		}

		///<summary>
		/// Show this page: Shows this page in the top navigation bar
		///</summary>
		[ImplementPropertyType("pageVisible")]
		public bool PageVisible
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetPageVisible(this); }
		}

		///<summary>
		/// Header Text: Your page header
		///</summary>
		[ImplementPropertyType("headerText")]
		public string HeaderText
		{
			get { return Umbraco.Web.PublishedContentModels.PageHeaderText.GetHeaderText(this); }
		}

		///<summary>
		/// Short Description: Short description of the element goes here
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return Umbraco.Web.PublishedContentModels.PageHeaderText.GetShortDescription(this); }
		}
	}
}
