//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, INavigation, IPageHeaderText
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Call to Action button
		///</summary>
		[ImplementPropertyType("aboutUsCtaButton")]
		public string AboutUsCtaButton
		{
			get { return this.GetPropertyValue<string>("aboutUsCtaButton"); }
		}

		///<summary>
		/// aboutUsDescription: Write about page here
		///</summary>
		[ImplementPropertyType("aboutUsDescription")]
		public string AboutUsDescription
		{
			get { return this.GetPropertyValue<string>("aboutUsDescription"); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("aboutUsHeader")]
		public string AboutUsHeader
		{
			get { return this.GetPropertyValue<string>("aboutUsHeader"); }
		}

		///<summary>
		/// Amenity 1: First feature from left
		///</summary>
		[ImplementPropertyType("amenity1")]
		public string Amenity1
		{
			get { return this.GetPropertyValue<string>("amenity1"); }
		}

		///<summary>
		/// Amenity 1 Header
		///</summary>
		[ImplementPropertyType("amenity1Header")]
		public string Amenity1Header
		{
			get { return this.GetPropertyValue<string>("amenity1Header"); }
		}

		///<summary>
		/// Amenity 2: Second feature
		///</summary>
		[ImplementPropertyType("amenity2")]
		public string Amenity2
		{
			get { return this.GetPropertyValue<string>("amenity2"); }
		}

		///<summary>
		/// Amenity 2 Header
		///</summary>
		[ImplementPropertyType("amenity2Header")]
		public string Amenity2Header
		{
			get { return this.GetPropertyValue<string>("amenity2Header"); }
		}

		///<summary>
		/// Amenity 3: Third feature
		///</summary>
		[ImplementPropertyType("amenity3")]
		public string Amenity3
		{
			get { return this.GetPropertyValue<string>("amenity3"); }
		}

		///<summary>
		/// Amenity 3 Header
		///</summary>
		[ImplementPropertyType("amenity3Header")]
		public string Amenity3Header
		{
			get { return this.GetPropertyValue<string>("amenity3Header"); }
		}

		///<summary>
		/// Amenity 4: Fourth feature
		///</summary>
		[ImplementPropertyType("amenity4")]
		public string Amenity4
		{
			get { return this.GetPropertyValue<string>("amenity4"); }
		}

		///<summary>
		/// Amenity 4 Header
		///</summary>
		[ImplementPropertyType("amenity4Header")]
		public string Amenity4Header
		{
			get { return this.GetPropertyValue<string>("amenity4Header"); }
		}

		///<summary>
		/// Background Image: Background Image for the landing page
		///</summary>
		[ImplementPropertyType("backgroundImage")]
		public IPublishedContent BackgroundImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("backgroundImage"); }
		}

		///<summary>
		/// Contact Us Description
		///</summary>
		[ImplementPropertyType("contactDataDescription")]
		public string ContactDataDescription
		{
			get { return this.GetPropertyValue<string>("contactDataDescription"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("contactDataEmail")]
		public string ContactDataEmail
		{
			get { return this.GetPropertyValue<string>("contactDataEmail"); }
		}

		///<summary>
		/// Contact Us Header
		///</summary>
		[ImplementPropertyType("contactDataHeader")]
		public string ContactDataHeader
		{
			get { return this.GetPropertyValue<string>("contactDataHeader"); }
		}

		///<summary>
		/// Phone Number: country code - area code - 123 - 123 - 123
		///</summary>
		[ImplementPropertyType("contactDataPhoneNumber")]
		public string ContactDataPhoneNumber
		{
			get { return this.GetPropertyValue<string>("contactDataPhoneNumber"); }
		}

		///<summary>
		/// Call to Action button: First button on the left
		///</summary>
		[ImplementPropertyType("ctaButton1")]
		public string CtaButton1
		{
			get { return this.GetPropertyValue<string>("ctaButton1"); }
		}

		///<summary>
		/// Call to Action button 2: Second button on the right
		///</summary>
		[ImplementPropertyType("ctaButton2")]
		public string CtaButton2
		{
			get { return this.GetPropertyValue<string>("ctaButton2"); }
		}

		///<summary>
		/// Home Page Featured Rooms: Pick featured rooms for the homepage here
		///</summary>
		[ImplementPropertyType("homePageFeaturedRooms")]
		public IEnumerable<IPublishedContent> HomePageFeaturedRooms
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("homePageFeaturedRooms"); }
		}

		///<summary>
		/// Main Header
		///</summary>
		[ImplementPropertyType("mainAmenitiesHeader")]
		public string MainAmenitiesHeader
		{
			get { return this.GetPropertyValue<string>("mainAmenitiesHeader"); }
		}

		///<summary>
		/// Meta Description: The meta description is what appears together with your site's name on a google search, it appears below the site name. The recommended length is 130 words
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta tags: Comma separated list that describes what your site is about. Modern browsers ignore this so it is not required. Not harmful to add though
		///</summary>
		[ImplementPropertyType("metaTags")]
		public string MetaTags
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetMetaTags(this); }
		}

		///<summary>
		/// Page Title: The Page title is what you see in the browser's tab
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetPageTitle(this); }
		}

		///<summary>
		/// Show this page: Shows this page in the top navigation bar
		///</summary>
		[ImplementPropertyType("pageVisible")]
		public bool PageVisible
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetPageVisible(this); }
		}

		///<summary>
		/// Header Text: Your page header
		///</summary>
		[ImplementPropertyType("headerText")]
		public string HeaderText
		{
			get { return Umbraco.Web.PublishedContentModels.PageHeaderText.GetHeaderText(this); }
		}

		///<summary>
		/// Short Description: Short description of the element goes here
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return Umbraco.Web.PublishedContentModels.PageHeaderText.GetShortDescription(this); }
		}
	}
}
