//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1105 with alias "pageHeaderText"
	/// <summary>Page Header Text</summary>
	public partial interface IPageHeaderText : IPublishedContent
	{
		/// <summary>Header Text</summary>
		string HeaderText { get; }

		/// <summary>Short Description</summary>
		string ShortDescription { get; }
	}

	/// <summary>Page Header Text</summary>
	[PublishedContentModel("pageHeaderText")]
	public partial class PageHeaderText : PublishedContentModel, IPageHeaderText
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageHeaderText";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageHeaderText(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageHeaderText, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header Text: Your page header
		///</summary>
		[ImplementPropertyType("headerText")]
		public string HeaderText
		{
			get { return GetHeaderText(this); }
		}

		/// <summary>Static getter for Header Text</summary>
		public static string GetHeaderText(IPageHeaderText that) { return that.GetPropertyValue<string>("headerText"); }

		///<summary>
		/// Short Description: Short description of the element goes here
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return GetShortDescription(this); }
		}

		/// <summary>Static getter for Short Description</summary>
		public static string GetShortDescription(IPageHeaderText that) { return that.GetPropertyValue<string>("shortDescription"); }
	}
}
